
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author bruno
 */
public class mainVentana extends javax.swing.JFrame {
    private  gestionbuses gestion;
    private  String archivo;

    /**
     * Creates new form mainVentana
     */
    public mainVentana(gestionbuses gestion, String archivo) {
        this.gestion = gestion;
        this.archivo = archivo;

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloVentana = new javax.swing.JLabel();
        gestionPasajeros = new javax.swing.JButton();
        gestionBuses = new javax.swing.JButton();
        gestionViajes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tituloVentana.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tituloVentana.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloVentana.setText("Llegamos Tarde S.A.");

        gestionPasajeros.setText("Gestion de Pasajeros");
        gestionPasajeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionPasajerosActionPerformed(evt);
            }
        });

        gestionBuses.setText("Gestion de Buses");
        gestionBuses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionBusesActionPerformed(evt);
            }
        });

        gestionViajes.setText("Gestion de Viajes");
        gestionViajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionViajesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(gestionPasajeros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tituloVentana, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                    .addComponent(gestionBuses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gestionViajes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(tituloVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gestionPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gestionBuses, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gestionViajes, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void gestionPasajerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionPasajerosActionPerformed
        GestionPasajerosVentana gPasajeros = new GestionPasajerosVentana(gestion, archivo);
        gPasajeros.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_gestionPasajerosActionPerformed

    private void gestionBusesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionBusesActionPerformed
        GestionBusesVentana gBuses = new GestionBusesVentana(gestion, archivo);
        gBuses.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_gestionBusesActionPerformed

    private void gestionViajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionViajesActionPerformed
        GestionViajesVentana gViaje = new GestionViajesVentana(gestion, archivo);
        gViaje.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_gestionViajesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton gestionBuses;
    private javax.swing.JButton gestionPasajeros;
    private javax.swing.JButton gestionViajes;
    private javax.swing.JLabel tituloVentana;
    // End of variables declaration//GEN-END:variables
}
