/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author bruno
 */
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
public class mostrarBusesVentana extends javax.swing.JFrame {
    private final gestionbuses gestion;
    private final String archivo;
    /**
     * Creates new form mostrarBusesVentana
     */
    public mostrarBusesVentana(gestionbuses gestion, String archivo) {
        this.gestion = gestion;
        this.archivo = archivo;

        initComponents();
        DefaultTableModel modeloTabla =
        (DefaultTableModel) tablaBuses.getModel();

        for (int i = 0; i < gestion.getCantidadBuses(); i++) {

            Buses bus = gestion.obtenerBus(i);

            modeloTabla.addRow(new Object[]{
                bus.getIdBus(),
                bus.getCapacity(),
                bus.getDisponibility()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaBuses = new javax.swing.JTable();
        backToBuses = new javax.swing.JButton();
        buscarBuses = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaBuses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID ", "Capacidad", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(tablaBuses);

        backToBuses.setText("Volver a Buses");
        backToBuses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToBusesActionPerformed(evt);
            }
        });

        buscarBuses.setText("Ingresa ID");
        buscarBuses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBusesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(backToBuses)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarBuses, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(buscarBuses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(backToBuses)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backToBusesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToBusesActionPerformed
        GestionBusesVentana gBuses = new GestionBusesVentana(gestion,archivo);
        gBuses.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backToBusesActionPerformed

    private void buscarBusesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBusesActionPerformed
         String texto = buscarBuses.getText().trim();

        if (texto.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Ingrese un ID para buscar.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        DefaultTableModel modeloTabla =
                (DefaultTableModel) tablaBuses.getModel();

        try {
            int id = Integer.parseInt(texto);

            Buses bus = gestion.buscarBus(id);

            modeloTabla.setRowCount(0);

            modeloTabla.addRow(new Object[]{
                bus.getIdBus(),
                bus.getCapacity(),
                bus.getDisponibility()
            });

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(
                    this,
                    "El ID debe ser un número.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE

            );

        } catch (ElementoNoEncontradoException e) {

            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_buscarBusesActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToBuses;
    private javax.swing.JTextField buscarBuses;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaBuses;
    // End of variables declaration//GEN-END:variables
}
