/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author bruno
 */

import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

public class mostrarViajesVentana extends javax.swing.JFrame {
    private gestionbuses gestion;
    private String archivo;
    /**
     * Creates new form mostrarViajesVentana
     */
    public mostrarViajesVentana(gestionbuses gestion, String archivo) {
        this.gestion = gestion;
        this.archivo = archivo;
        initComponents();
        
        cargarViajes();
    }
    
    private  void cargarViajes(){
        DefaultTableModel modeloTabla = (DefaultTableModel) jTable1.getModel();
        for (int i = 0; i < gestion.getCantidadViajes(); i++){
            Viajes viaje = gestion.obtenerViaje(i);
            modeloTabla.addRow(new Object[]{
                viaje.getIdViaje(),
                viaje.getOrigen(),
                viaje.getDestino(),
                viaje.getCostoViaje(),
                viaje.getCostoPasaje(),
                viaje.getCantidadBuses(),
                viaje.getFechaHoraInicio()
            });
            
        }
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        backMenu1 = new javax.swing.JButton();
        buscarViajes = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Origen", "Destino", "Costo Viaje", "Costo Pasaje", "Cantidad de buses", "Fecha y Hora"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        backMenu1.setText("Volver a viajes");
        backMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backMenu1ActionPerformed(evt);
            }
        });

        buscarViajes.setText("Inserte ID");
        buscarViajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarViajesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buscarViajes, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backMenu1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(buscarViajes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(backMenu1)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backMenu1ActionPerformed
        GestionViajesVentana gViajes = new GestionViajesVentana(gestion,archivo);
        gViajes.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_backMenu1ActionPerformed

    private void buscarViajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarViajesActionPerformed
       String texto = buscarViajes.getText().trim();

        if (texto.isEmpty()) {
            JOptionPane.showMessageDialog(
            this,
            "Ingrese un ID para buscar.",
            "Error",
            JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        DefaultTableModel modeloTabla =
                (DefaultTableModel) jTable1.getModel();

        try {
            int id = Integer.parseInt(texto);

            Viajes viaje = gestion.buscarViaje(id);

            modeloTabla.setRowCount(0);

            modeloTabla.addRow(new Object[]{
                viaje.getIdViaje(),
                viaje.getOrigen(),
                viaje.getDestino(),
                viaje.getCostoViaje(),
                viaje.getCostoPasaje(),
                viaje.getCantidadBuses(),
                viaje.getFechaHoraInicio()
            });

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(
                this,
                "El ID debe ser un número.",
                "Error",
                JOptionPane.ERROR_MESSAGE
            );

        } catch (ElementoNoEncontradoException e) {

            JOptionPane.showMessageDialog(
                this,
                e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_buscarViajesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backMenu1;
    private javax.swing.JTextField buscarViajes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
