/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author bruno
 */
import javax.swing.JOptionPane;
public class GestionPasajerosVentana extends javax.swing.JFrame {
    private gestionbuses gestion;
    private String archivo;
    /** Creates new form GestionPasajerosVentana */
    public GestionPasajerosVentana(gestionbuses gestion, String archivo) {
        this.gestion = gestion;
        this.archivo = archivo;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tituloVentana = new javax.swing.JLabel();
        deletePasajero = new javax.swing.JButton();
        addPasajero = new javax.swing.JButton();
        backMenu = new javax.swing.JButton();
        getPasajeros = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tituloVentana.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tituloVentana.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloVentana.setText("Gestion De Pasajeros");
        tituloVentana.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        deletePasajero.setText("Eliminar Pasajero");
        deletePasajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePasajeroActionPerformed(evt);
            }
        });

        addPasajero.setText("Agregar Pasajero");
        addPasajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPasajeroActionPerformed(evt);
            }
        });

        backMenu.setText("Volver al menu");
        backMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backMenuActionPerformed(evt);
            }
        });

        getPasajeros.setText("Mostrar Pasajeros");
        getPasajeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getPasajerosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(tituloVentana)
                    .addComponent(deletePasajero, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addPasajero, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(202, 202, 202))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(tituloVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(addPasajero, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deletePasajero, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(getPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(backMenu)
                .addGap(26, 26, 26))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void deletePasajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePasajeroActionPerformed
        String idTexto = JOptionPane.showInputDialog(
            this,
            "Ingrese ID del pasajero:"
        );
        try {
            int id = Integer.parseInt(idTexto);
            boolean resultado = gestion.eliminarPasajero(id);
            if (resultado) {
            JOptionPane.showMessageDialog(
                    this,
                    "Pasajero eliminado correctamente.",
                    "Éxito",
                    JOptionPane.INFORMATION_MESSAGE
                );
            } else {
                JOptionPane.showMessageDialog(
                        this,
                        "No se pudo eliminar el pasajero.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
            }
        } catch(NumberFormatException e ){
            JOptionPane.showMessageDialog(
                this,
                e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
        } catch (ElementoNoEncontradoException e) {

            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
            
        }
                
    }//GEN-LAST:event_deletePasajeroActionPerformed

    private void addPasajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPasajeroActionPerformed
        String idTexto = JOptionPane.showInputDialog(this, "Ingrese ID del pasajero:");
        int id = Integer.parseInt(idTexto);
        
        String nombre = JOptionPane.showInputDialog(this, "Ingrese nombre del pasajero:");
        
        String edadTexto = JOptionPane.showInputDialog(this, "Ingrese edad del pasajero:");
        int edad = Integer.parseInt(edadTexto);
        
        String origen = JOptionPane.showInputDialog(this, "Ingrese origen:");
        
        String destino = JOptionPane.showInputDialog(this, "Ingrese destino:");        
        
        String fechaHora = JOptionPane.showInputDialog(
            this, "Ingrese fecha y hora (dd/MM/yyyy HH:mm):" );
        
        boolean resultado = gestion.reservarViaje(
            id,
            nombre,
            edad,
            origen,
            destino,
            fechaHora
        );
        
        if (resultado) {
        JOptionPane.showMessageDialog(
                this,
                "Pasajero agregado correctamente.",
                "Éxito",
                JOptionPane.INFORMATION_MESSAGE
        );
        } else {
            JOptionPane.showMessageDialog(
                    this,
                    "No se pudo agregar el pasajero.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_addPasajeroActionPerformed

    private void backMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backMenuActionPerformed
        mainVentana main = new mainVentana(gestion,archivo);
        main.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_backMenuActionPerformed

    private void getPasajerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getPasajerosActionPerformed
        mostrarPasajerosVentana gPasajeros = new mostrarPasajerosVentana(gestion, archivo);
        gPasajeros.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_getPasajerosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPasajero;
    private javax.swing.JButton backMenu;
    private javax.swing.JButton deletePasajero;
    private javax.swing.JButton getPasajeros;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel tituloVentana;
    // End of variables declaration//GEN-END:variables

}