/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author bruno
 */
import javax.swing.JOptionPane;
public class GestionBusesVentana extends javax.swing.JFrame {
    private final gestionbuses gestion;
    private final String archivo;
    /**
     * Creates new form GestionBusesVentana
     */
    public GestionBusesVentana(gestionbuses gestion, String archivo) {
        this.gestion = gestion;
        this.archivo = archivo;

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        tituloVentana2 = new javax.swing.JLabel();
        addBus = new javax.swing.JButton();
        deleteBus = new javax.swing.JButton();
        getBuses = new javax.swing.JButton();
	modBus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButton3.setText("Volver al menu");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        tituloVentana2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tituloVentana2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloVentana2.setText("Gestion De Buses");
        tituloVentana2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        addBus.setText("Agregar Bus");
        addBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBusActionPerformed(evt);
            }
        });

        deleteBus.setText("Eliminar Bus");
        deleteBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBusActionPerformed(evt);
            }
        });

        getBuses.setText("Mostrar Buses");
        getBuses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getBusesActionPerformed(evt);
            }
        });

	modBus.setText("Modificar Bus");
	modBus.addActionListener(new java.awt.event.ActionListener() {
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		modBusActionPerformed(evt);
	    }
	});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(tituloVentana2)
                            .addComponent(deleteBus, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(getBuses, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addBus, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
			    .addComponent(modBus, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton3))
                .addContainerGap(231, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(tituloVentana2)
                .addGap(38, 38, 38)
                .addComponent(addBus, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteBus, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(getBuses, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
		.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		.addComponent(modBus, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jButton3)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        mainVentana main = new mainVentana(gestion, archivo);
        main.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void addBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBusActionPerformed
        String idTexto = JOptionPane.showInputDialog(
               this,
               "Ingrese ID del bus:"
       );

       String capacidadTexto = JOptionPane.showInputDialog(
               this,
               "Ingrese capacidad del bus:"
       );

       try {
           int id = Integer.parseInt(idTexto);
           int capacidad = Integer.parseInt(capacidadTexto);

           gestion.agregarBus(id, capacidad);

           JOptionPane.showMessageDialog(
                   this,
                   "Bus agregado correctamente.",
                   "Éxito",
                   JOptionPane.INFORMATION_MESSAGE
           );

       } catch (NumberFormatException e) {

           JOptionPane.showMessageDialog(
                   this,
                   "El ID y la capacidad deben ser números.",
                   "Error",
                   JOptionPane.ERROR_MESSAGE

           );

       } catch (IllegalArgumentException e) {

           JOptionPane.showMessageDialog(
                   this,
                   e.getMessage(),
                   "Error",
                   JOptionPane.ERROR_MESSAGE
           );
       }
    }//GEN-LAST:event_addBusActionPerformed

    private void deleteBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBusActionPerformed
        String idTexto = JOptionPane.showInputDialog(this, "Ingrese ID del bus:");

        try {
            int id = Integer.parseInt(idTexto);

            gestion.eliminarBus(id);

            JOptionPane.showMessageDialog(
                this,
                "Bus eliminado correctamente.",
                "Éxito",
                JOptionPane.INFORMATION_MESSAGE
            );

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(
                this,
                "El ID debe ser un número.",
                "Error",
                JOptionPane.ERROR_MESSAGE
            );

        } catch (ElementoNoEncontradoException e) {

            JOptionPane.showMessageDialog(
                this,
                e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
            );

        } catch (IllegalArgumentException e) {

            JOptionPane.showMessageDialog(
                this,
                e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_deleteBusActionPerformed

    private void getBusesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getBusesActionPerformed
        mostrarBusesVentana gBuses = new mostrarBusesVentana(gestion, archivo);
        gBuses.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_getBusesActionPerformed

    private void modBusActionPerformed(java.awt.event.ActionEvent evt) {
	String idTexto = JOptionPane.showInputDialog(this, "Ingrese ID del bus a modificar:");
	String capacidadTexto = JOptionPane.showInputDialog(this, "Ingrese la nueva capacidad");

	try {
	    int id = Integer.parseInt(idTexto);
	    int nuevaCapacidad = Integer.parseInt(capacidadTexto);

	    gestion.modificarBus(id, nuevaCapacidad);

	    JOptionPane.showMessageDialog(this, "Bus modificado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
	} catch (NumberFormatException e) {
	    JOptionPane.showMessageDialog(this, "El ID y la capacidad deben ser números", "Error", JOptionPane.ERROR_MESSAGE);
	} catch (ElementoNoEncontradoException e) {
	    JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
	} catch (IllegalArgumentException e) {
	    JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
	}
    }
    
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBus;
    private javax.swing.JButton deleteBus;
    private javax.swing.JButton getBuses;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton modBus;
    private javax.swing.JLabel tituloVentana2;
    // End of variables declaration//GEN-END:variables
}
