/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author bruno
 */
import javax.swing.JOptionPane;
import java.time.LocalDateTime;
import java.time.format.DateTimeParseException;
public class GestionViajesVentana extends javax.swing.JFrame {
    private gestionbuses gestion;
    private String archivo;
    /**
     * Creates new form GestionViajesVentana
     */
    public GestionViajesVentana(gestionbuses gestion, String archivo) {
        this.gestion = gestion;
        this.archivo = archivo;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backToMenu = new javax.swing.JButton();
        tituloVentana2 = new javax.swing.JLabel();
        addViaje = new javax.swing.JButton();
        deleteViaje = new javax.swing.JButton();
        getViajes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backToMenu.setText("Volver al menu");
        backToMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToMenuActionPerformed(evt);
            }
        });

        tituloVentana2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tituloVentana2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloVentana2.setText("Gestion De Viajes");
        tituloVentana2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        addViaje.setText("Agregar Viaje");
        addViaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addViajeActionPerformed(evt);
            }
        });

        deleteViaje.setText("Eliminar Viaje");
        deleteViaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteViajeActionPerformed(evt);
            }
        });

        getViajes.setText("Mostrar Viajes");
        getViajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getViajesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(tituloVentana2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backToMenu))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(addViaje, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteViaje, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(getViajes, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(208, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(tituloVentana2)
                .addGap(43, 43, 43)
                .addComponent(addViaje, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteViaje, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(getViajes, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(backToMenu)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backToMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToMenuActionPerformed
        mainVentana main = new mainVentana(gestion,archivo);
        main.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_backToMenuActionPerformed

    private void addViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addViajeActionPerformed
        String origen = JOptionPane.showInputDialog(this, "Ingrese el origen:");
        String destino = JOptionPane.showInputDialog(this, "Ingrese el destino:");
        String costoViajeTexto = JOptionPane.showInputDialog(this, "Ingrese el costo del viaje:");
        String costoPasajeTexto = JOptionPane.showInputDialog(this, "Ingrese el costo del pasaje:");
        String fechaTexto = JOptionPane.showInputDialog(this, "Ingrese fecha y hora (dd/MM/yyyy HH:mm):");
        String cantidadBusesTexto = JOptionPane.showInputDialog(this, "Ingrese cantidad de buses:");

        try {
            double costoViaje = Double.parseDouble(costoViajeTexto);
            double costoPasaje = Double.parseDouble(costoPasajeTexto);
            int cantidadBuses = Integer.parseInt(cantidadBusesTexto);

            LocalDateTime fechaHora = LocalDateTime.parse(
                fechaTexto,
                java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm")
            );

            Viajes viaje = gestion.agregarViaje(
                origen,
                destino,
                costoViaje,
                costoPasaje,
                fechaHora,
                cantidadBuses
            );

            JOptionPane.showMessageDialog(
                this,
                "Viaje agregado correctamente.\nID del viaje: " + viaje.getIdViaje(),
                "Éxito",
                JOptionPane.INFORMATION_MESSAGE
            );

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(
                this,
                "El costo y la cantidad de buses deben ser números.",
                "Error",
                JOptionPane.ERROR_MESSAGE
            );

        } catch (DateTimeParseException e) {

            JOptionPane.showMessageDialog(
                this,
                "La fecha debe tener el formato dd/MM/yyyy HH:mm.",
                "Error",
                JOptionPane.ERROR_MESSAGE
            );

        } catch (IllegalArgumentException e) {

            JOptionPane.showMessageDialog(
                this,
                e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_addViajeActionPerformed

    private void deleteViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteViajeActionPerformed
        String idTexto = JOptionPane.showInputDialog(
            this,
            "Ingrese ID del viaje:"
        );

        try {
            int id = Integer.parseInt(idTexto);

            gestion.eliminarViaje(id);

            JOptionPane.showMessageDialog(
                this,
                "Viaje eliminado correctamente.",
                "Éxito",
                JOptionPane.INFORMATION_MESSAGE
            );

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(
                this,
                "El ID debe ser un número.",
                "Error",
                JOptionPane.ERROR_MESSAGE
            );

        } catch (ElementoNoEncontradoException e) {

            JOptionPane.showMessageDialog(
                this,
                e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
            );

        } catch (IllegalArgumentException e) {

            JOptionPane.showMessageDialog(
                this,
                e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_deleteViajeActionPerformed

    private void getViajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getViajesActionPerformed
        mostrarViajesVentana mVentana = new mostrarViajesVentana(gestion , archivo);
        mVentana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_getViajesActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addViaje;
    private javax.swing.JButton backToMenu;
    private javax.swing.JButton deleteViaje;
    private javax.swing.JButton getViajes;
    private javax.swing.JLabel tituloVentana2;
    // End of variables declaration//GEN-END:variables
}
