/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author bruno
 */
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
public class mostrarPasajerosVentana extends javax.swing.JFrame {
    private gestionbuses gestion;
    private String archivo;
    /**
     * Creates new form mostrarPasajerosVentana
     */
    public mostrarPasajerosVentana(gestionbuses gestion, String archivo) {
        this.gestion = gestion;
        this.archivo = archivo;
        initComponents();
        cargarPasajeros();
    }
    
    private  void cargarPasajeros(){
        DefaultTableModel modeloTabla = (DefaultTableModel) jTable1.getModel();
        System.out.println("Cantidad de pasajeros: " + gestion.getCantidadPasajeros());
        for (int i = 0; i < gestion.getCantidadPasajeros(); i++){
            Pasajeros pasajero = gestion.obtenerPasajero(i);
            modeloTabla.addRow(new Object[]{
                pasajero.getIdPasajero(),
                pasajero.getNombre(),
                pasajero.getEdad(),
                pasajero.getBus()
            });
            
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        backMenu1 = new javax.swing.JButton();
        buscarPasajeros = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Edad", "Bus"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        backMenu1.setText("Volver a pasajeros");
        backMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backMenu1ActionPerformed(evt);
            }
        });

        buscarPasajeros.setText("Ingrese ID");
        buscarPasajeros.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        buscarPasajeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPasajerosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 785, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(backMenu1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buscarPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(buscarPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addComponent(backMenu1)
                .addContainerGap())
        );

        buscarPasajeros.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backMenu1ActionPerformed
        GestionPasajerosVentana gPasajeros = new GestionPasajerosVentana(gestion,archivo);
        gPasajeros.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backMenu1ActionPerformed

    private void buscarPasajerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPasajerosActionPerformed
          String texto = buscarPasajeros.getText().trim();

        if (texto.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Ingrese un ID para buscar.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        DefaultTableModel modeloTabla =
                (DefaultTableModel) jTable1.getModel();

        try {
            int id = Integer.parseInt(texto);

            Pasajeros pasajero = gestion.buscarPasajero(id);

            modeloTabla.setRowCount(0);

            modeloTabla.addRow(new Object[]{
                pasajero.getIdPasajero(),
                pasajero.getNombre(),
                pasajero.getEdad(),
                pasajero.getBus()
            });

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(
                    this,
                    "El ID debe ser un número.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );

        } catch (ElementoNoEncontradoException e) {

            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_buscarPasajerosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backMenu1;
    private javax.swing.JTextField buscarPasajeros;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
